name: CI for building WPT tests

on:
  # push:
  #   branches: [ main ]
  #   paths: [ .github/**, interpreter/**, test/** ]

  # pull_request:
  #   branches: [ main ]
  #   paths: [ .github/**, interpreter/**, test/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-wpt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14.x
      - name: Setup OCaml tools
        run: opam install --yes ocamlfind.1.9.5 js_of_ocaml.4.0.0 js_of_ocaml-ppx.4.0.0
      - name: Build interpreter
        run: cd interpreter && opam exec make
      - name: Convert WAST tests to WPT
        run: test/build.py --html out/
